import { useEffect, useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Plus, Printer, Save, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { AppShell } from "@/components/layout/app-shell";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useAuth } from "@/hooks/use-auth";

type Item={description:string;quantity:number;unitPrice:number;discount:number;tax:number};
type Draft={sellerName:string;sellerEmail:string;sellerAddress:string;customerName:string;customerEmail:string;customerAddress:string;invoiceNumber:string;invoiceDate:string;dueDate:string;notes:string;items:Item[]};
const newDraft=():Draft=>({sellerName:"",sellerEmail:"",sellerAddress:"",customerName:"",customerEmail:"",customerAddress:"",invoiceNumber:"INV-001",invoiceDate:new Date().toISOString().slice(0,10),dueDate:"",notes:"",items:[{description:"",quantity:1,unitPrice:0,discount:0,tax:0}]});
const money=(n:number)=>n.toLocaleString(undefined,{style:"currency",currency:"INR",minimumFractionDigits:2});
export const Route=createFileRoute("/_authenticated/invoice")({component:InvoicePage});
function InvoicePage(){
 const {user}=useAuth(); const storageKey="opti-invoice-draft-"+(user?.id||"local");
 const [draft,setDraft]=useState<Draft>(()=>{try{return JSON.parse(localStorage.getItem(storageKey)||"null")||newDraft()}catch{return newDraft()}});
 useEffect(()=>{localStorage.setItem(storageKey,JSON.stringify(draft))},[storageKey,draft]);
 const subtotal=useMemo(()=>draft.items.reduce((s,i)=>s+Math.max(0,i.quantity)*Math.max(0,i.unitPrice),0),[draft.items]);
 const discount=useMemo(()=>draft.items.reduce((s,i)=>s+Math.max(0,i.quantity)*Math.max(0,i.unitPrice)*Math.min(100,Math.max(0,i.discount))/100,0),[draft.items]);
 const tax=useMemo(()=>draft.items.reduce((s,i)=>{const base=Math.max(0,i.quantity)*Math.max(0,i.unitPrice)*(1-Math.min(100,Math.max(0,i.discount))/100);return s+base*Math.max(0,i.tax)/100},0),[draft.items]);
 const total=subtotal-discount+tax;
 const update=(field:keyof Draft,value:string)=>setDraft(d=>({...d,[field]:value}));
 const itemUpdate=(index:number,field:keyof Item,value:string)=>setDraft(d=>({...d,items:d.items.map((it,i)=>i===index?{...it,[field]:field==="description"?value:Number(value)||0}:it)}));
 const print=()=>{if(!draft.invoiceNumber.trim()||!draft.customerName.trim()||draft.items.some(i=>!i.description.trim()||i.quantity<=0||i.unitPrice<0)){toast.error("Add an invoice number, customer, and valid items first");return}window.print()};
 return <AppShell title="Invoice Generator" description="Create an invoice and print or save it as PDF." actions={<div className="flex gap-2"><Button variant="outline" onClick={()=>toast.success("Draft saved on this device")}><Save className="mr-2 size-4"/>Save draft</Button><Button onClick={print}><Printer className="mr-2 size-4"/>Print / Save PDF</Button></div>}>
 <div className="mb-6 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm text-muted-foreground"><strong className="text-foreground">Local draft mode:</strong> saved only in this browser. Server invoice history needs the separate Supabase migration. This is a normal invoice generator; it does not issue GST IRNs, QR codes, or government e-invoices.</div>
 <div className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_minmax(360px,0.9fr)]"><div className="space-y-6 print:hidden">
 <section className="rounded-2xl border border-border bg-card/60 p-5"><h2 className="mb-4 text-lg font-semibold">Invoice details</h2><div className="grid gap-4 sm:grid-cols-3"><Field label="Invoice number" value={draft.invoiceNumber} onChange={v=>update("invoiceNumber",v)}/><Field label="Invoice date" type="date" value={draft.invoiceDate} onChange={v=>update("invoiceDate",v)}/><Field label="Due date" type="date" value={draft.dueDate} onChange={v=>update("dueDate",v)}/></div></section>
 <section className="grid gap-6 rounded-2xl border border-border bg-card/60 p-5 sm:grid-cols-2"><Party title="From" name={draft.sellerName} email={draft.sellerEmail} address={draft.sellerAddress} set={(f,v)=>update(f,v)} /><Party title="Bill to" name={draft.customerName} email={draft.customerEmail} address={draft.customerAddress} set={(f,v)=>update(f,v)} /></section>
 <section className="rounded-2xl border border-border bg-card/60 p-5"><div className="mb-4 flex items-center justify-between"><h2 className="text-lg font-semibold">Products / services</h2><Button size="sm" variant="outline" onClick={()=>setDraft(d=>({...d,items:[...d.items,{description:"",quantity:1,unitPrice:0,discount:0,tax:0}]}))}><Plus className="mr-2 size-4"/>Add item</Button></div><div className="space-y-3">{draft.items.map((it,i)=><div key={i} className="grid gap-3 rounded-xl border border-border p-3 sm:grid-cols-[minmax(0,1.5fr)_70px_105px_85px_70px_36px]"><Cell label="Description"><Input value={it.description} maxLength={200} onChange={e=>itemUpdate(i,"description",e.target.value)}/></Cell><Cell label="Qty"><Input type="number" min="0" step="0.01" value={it.quantity} onChange={e=>itemUpdate(i,"quantity",e.target.value)}/></Cell><Cell label="Price"><Input type="number" min="0" step="0.01" value={it.unitPrice} onChange={e=>itemUpdate(i,"unitPrice",e.target.value)}/></Cell><Cell label="Discount %"><Input type="number" min="0" max="100" value={it.discount} onChange={e=>itemUpdate(i,"discount",e.target.value)}/></Cell><Cell label="Tax %"><Input type="number" min="0" max="100" value={it.tax} onChange={e=>itemUpdate(i,"tax",e.target.value)}/></Cell><Button aria-label="Remove item" variant="ghost" size="icon" className="self-end" disabled={draft.items.length===1} onClick={()=>setDraft(d=>({...d,items:d.items.filter((_,j)=>j!==i)}))}><Trash2 className="size-4"/></Button></div>)}</div></section>
 <section className="rounded-2xl border border-border bg-card/60 p-5"><Label>Notes / payment terms</Label><Textarea className="mt-2" rows={4} maxLength={2000} value={draft.notes} onChange={e=>update("notes",e.target.value)} /></section></div>
 <div className="invoice-print rounded-2xl border border-border bg-white p-6 text-slate-900 shadow-sm sm:p-8"><div className="flex items-start justify-between gap-4 border-b border-slate-200 pb-6"><div><p className="text-xs font-bold uppercase tracking-[0.2em] text-emerald-700">Invoice</p><h2 className="mt-2 text-2xl font-bold">{draft.sellerName||"Your business"}</h2><p className="whitespace-pre-line text-sm text-slate-500">{draft.sellerAddress||"Business address"}</p><p className="text-sm text-slate-500">{draft.sellerEmail}</p></div><div className="text-right text-sm"><p className="font-semibold">{draft.invoiceNumber||"Invoice number"}</p><p className="mt-2 text-slate-500">Issued {draft.invoiceDate||"—"}</p><p className="text-slate-500">Due {draft.dueDate||"—"}</p></div></div><div className="grid gap-4 border-b border-slate-200 py-6 sm:grid-cols-2"><div><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Bill to</p><p className="mt-1 font-semibold">{draft.customerName||"Customer name"}</p><p className="whitespace-pre-line text-sm text-slate-500">{draft.customerAddress}</p><p className="text-sm text-slate-500">{draft.customerEmail}</p></div></div><table className="w-full text-sm"><thead><tr className="border-b border-slate-200 text-left text-xs uppercase tracking-wider text-slate-400"><th className="py-3">Description</th><th className="py-3 text-right">Qty</th><th className="py-3 text-right">Rate</th><th className="py-3 text-right">Amount</th></tr></thead><tbody>{draft.items.map((it,i)=>{const amount=Math.max(0,it.quantity)*Math.max(0,it.unitPrice)*(1-Math.min(100,Math.max(0,it.discount))/100);return <tr key={i} className="border-b border-slate-100"><td className="py-3">{it.description||"Item description"}</td><td className="py-3 text-right">{it.quantity}</td><td className="py-3 text-right">{money(it.unitPrice)}</td><td className="py-3 text-right">{money(amount)}</td></tr>})}</tbody></table><div className="ml-auto mt-6 max-w-xs space-y-2 text-sm"><div className="flex justify-between text-slate-500"><span>Subtotal</span><span>{money(subtotal)}</span></div><div className="flex justify-between text-slate-500"><span>Discount</span><span>-{money(discount)}</span></div><div className="flex justify-between text-slate-500"><span>Tax</span><span>{money(tax)}</span></div><div className="flex justify-between border-t border-slate-200 pt-3 text-lg font-bold"><span>Total</span><span>{money(total)}</span></div></div>{draft.notes?<div className="mt-10 border-t border-slate-200 pt-5 text-sm"><p className="font-semibold">Notes</p><p className="mt-1 whitespace-pre-line text-slate-500">{draft.notes}</p></div>:null}<p className="mt-10 text-center text-xs text-slate-400">Normal invoice document — not a government e-invoice or GST IRN.</p></div></div></AppShell>;
}
function Field({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div><Label>{label}</Label><Input className="mt-1" type={type} value={value} onChange={e=>onChange(e.target.value)}/></div>}
function Cell({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="mt-1">{children}</div></div>}
function Party({title,name,email,address,set}:{title:string;name:string;email:string;address:string;set:(f:keyof Draft,v:string)=>void}){return <div><h2 className="mb-4 text-lg font-semibold">{title}</h2><div className="space-y-3"><Field label="Name" value={name} onChange={v=>set(title==="From"?"sellerName":"customerName",v)}/><Field label="Email" type="email" value={email} onChange={v=>set(title==="From"?"sellerEmail":"customerEmail",v)}/><div><Label>Address</Label><Textarea className="mt-1" rows={3} value={address} onChange={e=>set(title==="From"?"sellerAddress":"customerAddress",e.target.value)}/></div></div></div>}
