import { useState } from "react";
import { Bot, MessageCircle, Send, X } from "lucide-react";
import { askChatbot } from "@/lib/chat.functions";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";

type Message={role:"user"|"assistant";text:string};
export function Chatbot(){const [open,setOpen]=useState(false);const [value,setValue]=useState("");const [pending,setPending]=useState(false);const [messages,setMessages]=useState<Message[]>([{role:"assistant",text:"Hi — I can explain your OptiSite audits, SEO, performance, accessibility, UX, security recommendations, and invoices."}]);
 async function send(e:React.FormEvent){e.preventDefault();const message=value.trim();if(!message||pending)return;setValue("");setMessages(m=>[...m,{role:"user",text:message}]);setPending(true);try{const result=await askChatbot({data:{message}});setMessages(m=>[...m,{role:"assistant",text:result.answer}])}catch(error){setMessages(m=>[...m,{role:"assistant",text:error instanceof Error?error.message:"I could not answer right now. Please try again."}])}finally{setPending(false)}}
 return <><Button aria-label="Open AI assistant" onClick={()=>setOpen(true)} className="fixed bottom-5 right-5 z-50 size-12 rounded-full shadow-lg print:hidden"><MessageCircle className="size-5"/></Button>{open?<div className="fixed bottom-20 right-5 z-50 flex h-[min(32rem,calc(100dvh-7rem))] w-[min(24rem,calc(100vw-2rem))] flex-col overflow-hidden rounded-2xl border border-border bg-background shadow-2xl print:hidden"><div className="flex items-center justify-between border-b border-border px-4 py-3"><div className="flex items-center gap-2"><Bot className="size-4 text-primary-glow"/><div><p className="text-sm font-semibold">OptiSite assistant</p><p className="text-[11px] text-muted-foreground">AI guidance — verify important advice</p></div></div><Button variant="ghost" size="icon" aria-label="Close assistant" onClick={()=>setOpen(false)}><X className="size-4"/></Button></div><div className="flex-1 space-y-3 overflow-y-auto p-4">{messages.map((m,i)=><div key={i} className={m.role==="user"?"ml-6 rounded-xl bg-primary p-3 text-sm text-primary-foreground":"mr-4 rounded-xl bg-muted p-3 text-sm text-foreground"}>{m.text}</div>)}{pending?<div className="mr-4 rounded-xl bg-muted p-3 text-sm text-muted-foreground">Thinking…</div>:null}</div><form onSubmit={send} className="flex gap-2 border-t border-border p-3"><Input value={value} maxLength={2000} onChange={e=>setValue(e.target.value)} placeholder="Ask about an audit…" aria-label="Ask the assistant"/><Button type="submit" size="icon" disabled={pending||!value.trim()} aria-label="Send message"><Send className="size-4"/></Button></form></div>:null}</>}
